### ISSUE TITLE
POV data not saved in ini file

### ISSUE THREAD

**Issue by Crrispy** [vpinball/vpinball#1025]
**Describe the bug**

When editing the POV (at least in Window mode) , pressing the start button says that the <table name>.ini file has been saved. But there is no pov related data in it. Example of the content of the ini file after saving:

[Player]
BallTrail = 0
BallTrailStrength = 0.000000

**To Reproduce**
1. Start any table
2. Go to adjust camera
3. Switch to Window mode
4. Make any adjustments to the POV
5. Press Start button, it will say that the .ini file has been saved
6. Check the ini file. There's no POV data in it. You still have to save the table, VPX will tell it has been modified.

**Expected behavior**
POV parameters should be in the ini file

**Versions & Settings**
 - VPX: 10.8 x64 build 1663
 - Windows version: 11 with October updates
 - GPU and video settings : RT4070Ti, 4K120Hz playfield

Settings:
[VPinballX.txt](https://github.com/vpinball/vpinball/files/13198870/VPinballX.txt)

**Comment by vbousquet** [comment]
Fixed in latest (refactoring of settings still in progress though)

**Comment by Crrispy** [comment]
> Fixed in latest (refactoring of settings still in progress though)

Hello Vincent, 

Sorry but it still doesn't work in 1696. I just tried with Elvis, after editing and saving the POV (osd says the .ini file was saved when pressing the start button), here is the content of the .ini file:

[Player]
BallTrailStrength = 0.392157

[TableOverride]
OverrideEmissionScale = 1

And that's it, no POV info.
