### ISSUE TITLE
DMDext (Freezy) Not Showing On Top of Playfield

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#1192]
**Describe the bug**
In the past, the DMDext (Freezy external DMD) has shown on top of the playfield... it even has a feature to specifically allow this.  In the wake of recent changes to allow things like mixer and sprites to show over the playfield as they have in the past, I noticed that this problem also exists with the DMDext.  It was mentioned to me that there are other elements, such as settings screens that are also having this problem, although I can't comment on this personally... it seems like more things could benefit from the same treatment as the mixer, etc...

**To Reproduce**
Load DMDext with "stay on top" setting = true on any table.  DMD will flash as it launches, and then immediately disappear behind the playfield on any table in exclusive full screen.

**Expected behavior**
As in the past, the external DMD (Freezy) should display on top of the playfield in exclusive fullscreen.

**Versions & Settings**
 - VPX: dx64 rev 1804 and earlier
 - Windows 11
 - GPU 4060
[VPinballX.log](https://github.com/vpinball/vpinball/files/13461628/VPinballX.log)

**Comment by wiesshund** [comment]
Should not appear on top in exclusive fullscreen, as it is exclusive
unless using windows fullscreen optimization maybe?

but i have that disabled, and even 10.7.3 does not allow dmd to show when exclusive fullscreen is enabled
It may with that on since windows forces it to be fullscreen windowed

**Comment by Drybonz** [comment]
It definitely did used to show on top in exclusive fullscreen using the "show on top" setting, as this was the only reason I used it.  I remember having this conversation with you on VPF in the past, you telling me it wasn't possible, and then solving it this way.

Regardless, it doesn't work now.

**Comment by kbtbc** [comment]
Possibly previously reported, and fixed by https://github.com/vpinball/vpinball/pull/1174

**Comment by Drybonz** [comment]
Are you saying that it is working for you, kbtbc?  1173/1174 is similar but does not fix this issue.

**Comment by wiesshund** [comment]
> It definitely did used to show on top in exclusive fullscreen using the "show on top" setting, as this was the only reason I used it. I remember having this conversation with you on VPF in the past, you telling me it wasn't possible, and then solving it this way.
> 
> Regardless, it doesn't work now.

If it is truly exclusive full screen and not borderless full screen windowed, then nothing should be able to appear on top
or else it is not exclusive.

Never worried about it because i never used it (trying to put a external DMD over top of the table)
in desktop view i just display DMD in table if using 1 screen.
Too hard to try to position one anyways being that in exclusive full screen, there is no cursor on the playfield screen
only backglass and dmd screens

**Comment by christianonpele** [comment]
Just had the same problem after update to 1807. Please try to hit F3 ingame to make Freezy's DMD visible. 
After you switch input API from Direct Input to xinput , you should see the DMD permanetely back on top. (Visual Pinball -> Preferences -> Config. Keys Nudge)

**Comment by Drybonz** [comment]
Good call, christianonpele... switching to xinput did work for me.  Freezy will stay on top in exclusive fullscreen desktop with xinput selected (but not dinput).  Not sure if this will be considered a fix or a workaround... will leave it up to the vpx team.  Thanks, christianonpele for the help troubleshooting.

**Comment by vbousquet** [comment]
Closed as a duplicate of https://github.com/vpinball/vpinball/issues/2466
