### ISSUE TITLE
Runtime error back to future table

### ISSUE THREAD

**Issue by keithhov** [vpinball/vpinball#1525]
script error when engaging flippers only on back to the future 
' VPX version 1.0 - cyberpez

 Runtime error
-------------
Line: 1
Out of stack space: 'vpmFlips.RomFlip'

version 1907 GL with pinmame 862

**Comment by keithhov** [comment]
get this error as well....

Runtime error
-------------
Line: 1
Out of stack space: 'cb'

**Comment by vbousquet** [comment]
Fixed in latest

**Comment by keithhov** [comment]
@vbousquet   still getting error in 1911... seems to be only table out of about 200 that has an issue since 1910

**Comment by vbousquet** [comment]
Latest is master/1910, build marked 10.8.1 are not supposed to be stable or even usable since these are very early pre-alpha builds
