### ISSUE TITLE
Ball artifacts on elasticity test table

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#2446]
BGFX
Linux
master

```
./build/VPinballX_BGFX -play ./tables/JP\'s\ VPX7\ Rev3\ Elasticity_Test.vpx
```

I'm getting strange ball artifacts:

![Image](https://github.com/user-attachments/assets/6d4e91e1-57b8-409d-b160-f28ea5121eb6)

**Comment by toxieainc** [comment]
Related to Motion Blur? Or the Ball Trails?

**Comment by francisdb** [comment]
Above was with `BallTrail = 0`

**Comment by francisdb** [comment]
This is with a default config on a different linux pc XWayland / Vulkan (even more visible squares follow the ball)

![Image](https://github.com/user-attachments/assets/d9fd6908-f8c0-4aee-8567-bf02600030c8)

**Comment by francisdb** [comment]
The quad halo has already been reported in #2076

**Comment by joni999** [comment]
Hi,
I can't replicate this issue on Linux with a fresh VPX 10.8.1 build and a fresh VPinballX.ini
Am I missing something or has this been fixed already?

**Comment by francisdb** [comment]
Closing as this probably has been fixed

**Comment by gjupp** [comment]
> Closing as this probably has been fixed

Similar issue still exists in VR. Turning off motion blur fixes the issue.

**Comment by vbousquet** [comment]
This was caused by the raytraced ball motion blur which is disabled until fully fixed, so closing
