### ISSUE TITLE
Missing lots of parameters Iron Man Vault Edition VPW v1.0 starting with 10.8.0 rev 589

### ISSUE THREAD

**Issue by passionforpins** [vpinball/vpinball#247]
**Describe the bug**
Missing parameters as follows;
elasticityFalloff is missing
playfieldScatter ""
defaultElementScatter ""
flipper speed ""
flipper strength ""
flipper elasticity ""
flipper scatter ""
flipper eosTorque ""
flipper eosTorqueAngle ""
flipper returnStrength ""
flipper elasticityFalloff ""
flipper friction ""
flipper coilRampUp ""

**To Reproduce**
Open Iron Man Vault Edition VPW v1.0 with vpx 10.8.0 beta rev 589 or newer and click play table

**Expected behavior**
Versions rev 580 and prior work as expected

**Screenshots**
NA

**Crash dump**
NA

**Versions**
 - VPX: VPinballX-10.8.0-589-8661034-Release-win-x86
 - VPinMAME-sc-3.6-261-8ac38ae-win-x86 
 - Windows version 10 Home 64 22h2
 - GPU Nvidia GTX 1060 6GB

**Comment by passionforpins** [comment]
Fixed with 10.8.0 rev 697- thanks and can be closed

**Comment by passionforpins** [comment]
NOT fixed, worked once but not after repeated tries

**Comment by vbousquet** [comment]
Iron Man Vault Edition VPW v1.0 is unlikely to work with the x86 version of VPX. This table needs to be ran with the x64 version.
Does the problem still happen for you with the x64 version ?
If so, could you post a screenshot ?

**Comment by passionforpins** [comment]
Yes it works fine with 64 bit version Vince- but then no pup pack :) 
Thanks! Will close

**Comment by toxieainc** [comment]
Sidenote: You could try reducing texture sizes to make it work with x86. btw: I can run it on my machine in x86, make sure to close all browsers, etc.
