### ISSUE TITLE
BGFX Linux - With HDR enabled, parts of playfield and/or cabinet are black on some tables

### ISSUE THREAD

**Issue by joni999** [vpinball/vpinball#2498]
**Describe the bug**
Parts of the playfield or cabinet are black when HDR is enabled

Using up to date CachyOS (Arch Linux) with KDE 6.3.5

**To Reproduce**
1) Enable HDR 
2) Start one of the following tables:
https://vpuniverse.com/files/file/24788-dragonball-super-saiyan-edition-original-2025-v105/
https://vpuniverse.com/files/file/16087-the-mandalorian/
https://vpuniverse.com/files/file/12652-tales-of-the-arabian-nights-4k-williams-1996/

I launch them with
`/usr/bin/VPinballX_BGFX -Play Table.vpx`

**Expected behavior**
No black parts of the playfield / cabinet

**Screenshots**
It's especially bad in the dragonball and mandalorian table where it looks like this:

![Image](https://github.com/user-attachments/assets/c526038e-7569-485f-bc24-f37c6901b229)

And it's less noticeable e.g. in Tales of the arabian nights where mostly just the cabinet is black.

**Versions & Settings**
Logfile: [logfile.txt](https://github.com/user-attachments/files/20578381/logfile.txt)
Ini (renamed to be able to upload): [VPinballX.ini.txt](https://github.com/user-attachments/files/20578358/VPinballX.ini.txt)

Up to date BGFX on CachyOS(Arch Linux) with commit [f79f15c](https://github.com/vpinball/vpinball/commit/f79f15c2d0cf3556efaec8b69d3e7098252aa55e)
GfxBackend = Direct3D11
Nvidia RTX 3090ti

It might have something to do with Nvidia - maybe someone with an AMD GPU can verify

**Comment by jsm174** [comment]
If you go back to 0205ebc1e03eede8a20bf89cd4032d6219d623cd does it work?

Also, if your on Linux, `Direct3D11` is not valid as this is a Windows specific technology.

You should be using `Vulkan` or `OpenGL`

**Comment by joni999** [comment]
I tried with the commit you mentioned but pretty much all tables I try crash with "Segmentation fault" except for Tales of the arabian nights for some reason - also happens with HDR turned off.

Logfile:
https://pastebin.com/DnhYyyTj

Also switched to Vulkan now - no idea why I had set Direct3D11 but it worked very well so far (no idea what the fallback is).

**Comment by kimmot** [comment]
Isn't this the same as you @jsm174 have commented here: https://github.com/vpinball/vpinball/commit/303e81ab96575c6ca5136a497a279fe95b12bc47
I noticed strange darkness with multiple tables using Linux BGFX (Nvidia 5070) build and based git bisecting "BGFX: compute irradiance map on the GPU" 303e81a commit caused my problems.

**Comment by toccata10** [comment]
For me #2491 is causing the same problems: black zones with Vulkan on linux.

with https://github.com/vpinball/vpinball/actions/runs/15378708535, it's fine:
![Image](https://github.com/user-attachments/assets/c680039b-596a-4cf1-b67b-9a0d145c6263)

with https://github.com/vpinball/vpinball/actions/runs/15379026514, it causes black zones:
![Image](https://github.com/user-attachments/assets/c14f6abd-ff5c-4670-811d-03f57dcd284a)

As a side note, after the irradiance PR, only  
GfxBackend = OpenGL gives a correct playfield. If I put Metal, Direct3D11, Vulkan... it's always black. I know I'm not supposed to put Direct3D11 in Linux, but it's just strange this produces the same incorrect result as Vulkan.

As another side note: 
`prime-run ./VPinballX_BGFX -play /mnt/jo/SHARE/roms/vpinball/Avengers\ Pro\ \(Stern\ 2012\)/Avengers\ Pro\ \(Stern\ 2012\)\ v1.48.vpx`  with `GfxBackend = OpenGL` crashes with
```
[RenderDevice::RenderDevice@713] Using graphics backend: OpenGL (available: Noop, Direct3D11, Direct3D12, OpenGL, Vulkan)
2025-06-04 23:02:19.075 ERROR [9941] [tBGFXCallback::fatal@62] /home/runner/work/vpinball/vpinball/external/linux-x64/Release/bgfx/bgfx.cmake/bgfx/src/glcontext_egl.cpp:425BGFX FATAL 2: Failed to create surface.
/usr/bin/prime-run: line 2:  9902 Aborted                 (core dumped) __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
```

**Comment by toccata10** [comment]
for me, it's now fixed with #2510

**Comment by joni999** [comment]
Yep! for me too - thank you guys for the quick fix!

**Comment by jsm174** [comment]
Glad this is working on Linux!  I'm going to re-open as Apple platforms are still having some strange behavior.

I found some old messages, and this commit fixed where we had issues with irradiance before:

https://github.com/vpinball/vpinball/commit/37cb9b35adf20eef3f56778f1375a3e1940651f4

As of now, here's a video, of back to back to back runs:

https://github.com/user-attachments/assets/5f83124b-b6fd-4c54-8643-8cbd7838a6a4

**Comment by toxieainc** [comment]
Could this be fixed by Vinces latest commit?

**Comment by jsm174** [comment]
Yes!

The latest commit goes back to CPU for irradiance for Apple platforms. 

I would like to revisit it someday as it must be a precision issue?  Vincent tried a few different things, but all the same behavior.

On the Mac, I can't rapidly test changing the shader code as it can't build the Direct3D ones. (They seem to be needed to get a successful compile). So I need to come up with a way to build them locally.

Fwiw, this was the current generated metal shader code:

```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct xlatMtlMain_out
{
    float4 bgfx_FragData0 [[color(0)]];
};

struct xlatMtlMain_in
{
    float2 v_texcoord0 [[user(locn0)]];
};

fragment xlatMtlMain_out xlatMtlMain(
    xlatMtlMain_in in           [[stage_in]],
    texture2d<float> tex_env    [[texture(1)]],
    sampler          tex_envSampler [[sampler(1)]])
{
    xlatMtlMain_out out = {};

    float _427 = 3.1415927410125732421875 + (in.v_texcoord0.x * 6.283185482025146484375);
    float _430 = in.v_texcoord0.y * 3.1415927410125732421875;
    float _435 = sin(_430) * cos(_427);
    float _440 = sin(_430) * sin(_427);
    float _442 = cos(_430);

    float3 _686 = float3(0.0);
    float3 _470;

    for (int _685 = 0; _685 < 32768; _686 = _470, _685++)
    {
        float _452 = float(_685) * 3.0517578e-05;
        float _496 = fract(float(_685) * 0.486328125) * 6.283185482025146484375;
        float _499 = sqrt(1.0 - _452);
        float _501 = sqrt(_452);
        float _508 = cos(_496) * _501;
        float _512 = sin(_496) * _501;
        float3 _687;

        do
        {
            if (_440 > -0.9999986419677734375)
            {
                float _527 = 1.0 / (1.0 + _440);
                float _530 = _527 * _442;
                float _533 = _530 * _435;
                _687 = float3(
                    _508 * (_440 + (_530 * _442)) + _499 * _533 - _512 * _533,
                    _499 * _440 - _508 * _435 - _512 * _442,
                    _499 * _442 - _508 * _442 + _512 * (_440 + (_527 * _435) * _435)
                );
                break;
            }
            else
            {
                _687 = -float3(_508, _435, _512);
                break;
            }
        } while (false);

        float _688;
        do
        {
            float _601 = abs(_687.y);
            float _602 = abs(_687.x);
            if (_602 <= 6.103515625e-05 && _601 <= 6.103515625e-05)
            {
                _688 = 0.0;
                break;
            }
            float _616 = (_602 - _601) / (_602 + _601);
            float _630 = ((_687.x < 0.0) ? 0.375 : 0.125)
                       + (((0.0337198336635557861328125 * _616) * _616)
                          - 0.1571344733323822021484375)
                         * ((_687.x < 0.0) ? -_616 : _616);
            _688 = (_687.y < 0.0) ? -_630 : _630;
            break;
        } while (false);

        float _689;
        do
        {
            float _645 = abs(_687.z);
            if (1.0 - _645 <= 6.103515625e-05)
            {
                _689 = (_687.z >= 0.0) ? 0.0 : 1.0;
                break;
            }
            float _659 = (((-0.049647428095340728759765625) * _645)
                         + 0.498049914836883544921875)
                        * sqrt(1.0 - _645);
            _689 = (_687.z >= 0.0) ? _659 : (1.0 - _659);
            break;
        } while (false);

        _470 = _686
             + tex_env.sample(tex_envSampler,
                              float2(0.5 + _688, _689),
                              level(0.0)
                             ).xyz
               * 3.0517578e-05;
    }

    out.bgfx_FragData0 = float4(_686, 1.0);
    return out;
}
```

This was the source as of writing this:

```
void main()
{
   // Compute sample direction
   const float phi   = PI + v_texcoord0.x * (2.0 * PI);
   const float theta =      v_texcoord0.y        * PI;
   const vec3 N = vec3(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));

   // Monte Carlo integration of hemispherical radiance -> irradiance
   const int NumSamples = 32768; // Limit to 32768 or 65536, will fail on macOS Metal otherwise
   const float InvNumSamples = 1.0 / float(NumSamples);
   const float g = 15936.0 / float(NumSamples); // 25962 = matching rank-1 generator constant for 65536 samples, 15936 for 32768 samples
   vec3 irradiance = vec3_splat(0.);
   for (int i=0; i<NumSamples; ++i) {
      //const vec2 u = vec2(float(i) * InvNumSamples, radicalInverse_VdC(i));
      const vec2 u = vec2(float(i) * InvNumSamples, fract(float(i) * g));
      const vec3 Li = rotate_to_vector_upper(cos_hemisphere_sample(u), N);
      const vec2 uv = ray_to_equirectangular_uv(Li);
      irradiance += texNoLod(tex_env, uv).rgb * InvNumSamples;
   }
   gl_FragColor = vec4(irradiance, 1.0);
}

```

**Comment by toxieainc** [comment]
I looked into a bit more, but i fail to see why this would be special on all Apples, as i would assume that the non-mobile hardware would not trigger the use of fp16 math.
Unfortunately, there is also no low hanging fruit to simplify the triggered math substantially (i.e. inlining and trying to combine math ops).

**Comment by vbousquet** [comment]
Removed the bug label, as I'm trying to figure what is left before 10.8.1 and this bug has a workaround now and is more an improvment issue

**Comment by jsm174** [comment]
If there is anything specific I could provide with the metal debug tool, just let me know. I know it has a ton of detail, I just don't know what I'm looking for 😄
