### ISSUE TITLE
VPX crashing on Win 11

### ISSUE THREAD

**Issue by jueank** [vpinball/vpinball#2502]
**Edit:** I changed the description. I thought the issue occurs only under certain conditions, but I figured it is happening in many more cases.

VPX crashes ~~when selecting any of the surround "multi-channel output" options in the Audio Options dialog. VPX runs fine when using the "Standard 2 channel" option.~~

**The issue also occurs on a clean Windows 11 installation. (only with a basic VPX setup. See below)**

**Observations:**
- The issue occurs only on Windows 11.
- VPX crashes when loading a table in the editor — you don't have to start playing the table (pressing F5).
- The issue only happens on some tables, but then consistently. Other tables can be loaded and played fine.
- I never experienced this behavior on Windows 10. (Same Hardware, same Pinball software installation (VPX, VPinMAME, B2SServer, etc.). My setup was running fine before under Windows 10.

vpinball.log does not contain any entry. It simply stops at a point where it otherwise continues when the crash does not happen.
I have a crash.dmp available, but it's 440MB compressed. If needed, I can share it.

Since I recently upgraded from Windows 10 to Windows 11, I suspected a problem with my system configuration rather than VPX itself. To rule that out, I performed a clean installation of Windows 11 with minimal modifications:

**This is all I did for the installation:**
- Windows version: Win11_24H2_German_x64.iso
- DirectX: directx_Jun2010_redist.exe
- Visual C++ Runtimes: Visual-C-Runtimes-All-in-One-Nov-2024.zip
- NVidia and Intel display drivers
- VPX: VPinballX_GL-10.8.0-2051-28dd6c3-Release-win-x64
- VPinMAME: 3.6.0
- B2SServer: 2.1.3
- Registered VPinMAME & B2SServer

Example table affected: Alien Star (3.0.1 by UnclePaulie).

Since everything worked flawlessly on the same hardware under Windows 10, it seems likely that this is a compatibility issue related to Windows 11 — possibly within DirectX, the audio subsystem, or related system components.

That said, it would be great if VPX could log the crash or handle it more gracefully — for example, by catching the error and failing safely rather than crashing outright.

vpinball.log:

> 2025-05-28 22:55:55.186 INFO  [8748] [VPApp::InitInstance@630] Starting VPX - v10.8.0 Final (Rev. 2051 (28dd6c3), windows OpenGL 64bits)
2025-05-28 22:55:55.242 INFO  [8748] [VPinball::OnInitialUpdate@1670] OnInitialUpdate
2025-05-28 22:55:55.262 INFO  [8748] [AudioMusicPlayer::InitPinDirectSound@513] Initializing BASS device #-1 [Reinit: 0]
2025-05-28 22:56:02.268 INFO  [8748] [PinTable::LoadGameFromFilename@3496] LoadGameFromFilename C:\Visual Pinball\Tables\Sorcerer (Williams 1985) v4.0.4.vpx
2025-05-28 22:56:02.269 INFO  [8748] [Settings::LoadFromFile@38] Settings file was loaded from 'C:\Visual Pinball\Tables\Sorcerer (Williams 1985) v4.0.4.ini'
2025-05-28 22:56:02.868 INFO  [8748] [PinTable::LoadGameFromFilename@3620] LoadData loaded
2025-05-28 22:56:03.218 INFO  [8748] [PinTable::LoadGameFromFilename@3655] GameItem loaded
2025-05-28 22:56:06.527 INFO  [8748] [PinTable::LoadGameFromFilename@3673] Sound loaded
2025-05-28 22:56:15.015 INFO  [8748] [PinTable::LoadGameFromFilename@3755] Image loaded
2025-05-28 22:56:15.017 INFO  [8748] [PinTable::LoadGameFromFilename@3778] Font loaded
2025-05-28 22:56:15.037 INFO  [8748] [PinTable::LoadGameFromFilename@3801] Collection loaded
2025-05-28 22:56:15.293 INFO  [8748] [PinTable::LoadGameFromFilename@3809] IEditable PostLoad performed
2025-05-28 22:56:15.371 INFO  [8748] [PinTable::InitTablePostLoad@1615] InitTablePostLoad

crash.txt:

> Crash report VPX - v10.8.0 Final (Rev. 2051 (28dd6c3), windows OpenGL 64bits)
============
Process: VPinballX.exe
Reason: 0xC0000005 - EXCEPTION_ACCESS_VIOLATION at 0033:00000001403A43EC
Attempt to read from 0x00000C48
Thread ID: 0x18E0 [6368]

> Call stack
==========
00000000403A43EC  (0x0014E880 0x00000000 0x00000000 0x00000000)

> Environment
===========
Date/time: 4/6/2025, 15:49:29:483
Number of CPUs: 4
Processor type: 8664
System: Windows 10 (10.0 26100)

> Memory status
=============
Total Reserved: 101340K (98M) bytes
Total Commited: 2876972K (2809M) bytes
Total Free: 1215928K (1187M) bytes
Largest Free: 2054248K (2006M) bytes

> Registers
=========
RAX=0014E880 RBX=0014C970 RCX=00000000 RDX=0014E450
RSI=0014D160 RDI=0014BD00 RBP=0014E450 RSP=0014AEF0 RIP=403A43EC
FLG=00010246 CS=0033 DS=002B SS=002B ES=002B FS=0053 GS=002B

> Mini dump saved successfully.

**Comment by jueank** [comment]
Perhaps the wording of my error description is too long.

At its core, I want to say the following: 
Even with a fresh and clean installation of Windows 11, VPX crashes ~~when surround sound is used~~. I believe this indicates an issue that should be investigated.

**Comment by jueank** [comment]
I’ve continued to investigate the issue.

At this point, the error occurs regardless of which sound option is selected and whether another program (like PinballY) is running in the background. I suspect that the mentioned components are using up system resources (to put it vaguely).

The new releases of CFTBL and Scared Stiff, for example, both crash during loading on Windows 11. In general, it seems that the more demanding tables (VPW, etc.) with large .vpx files fail to load in about two out of three cases - they crash during the loading process.

One further observation: if I reduce the maximum texture size to 1024 (which results in extremely low-quality, pixelated textures), the tables in question can be loaded successfully.

Some of the tables will eventually load after 3–4 crash attempts.

Another observation: When I have already one table open in the editor and I try to load one of the not working tables into the editor, VPX does not crash, but loading the table simply fails silently. This takes 10 - 15 seconds. I can continue to use the already loaded table.

My suspicion is that my issue is identical or closely related to this reported bug:
https://github.com/vpinball/vpinball/issues/2462

The behavior described above never occurred under Windows 10, using the same versions of VPX, VPinMAME, and B2S.
I suspect that something has changed in Windows 11 which negatively affects the stability of VPX.

**Comment by Squall-Leonhart** [comment]
The default DirectSound audio renderer cannot handle system mixers configured beyond 96khz, try with Xaudio instead if you are attached or outputting to a Dolby Atmos (192khz+) AVR or headset.

Also set the pagefile to a respectable size, Total Committed exceeds Total Free in your log.

**Comment by vbousquet** [comment]
Tha audio layer of VPX has been more or less entirely rewritten. Maybe it is now working ? If you could give a try and report back to see how it goes now, this would be nice

**Comment by jueank** [comment]
Thanks, @vbousquet, for your comment to my bug report.

I check the commits to VPinball daily and I'm having a look at the 10.8.1 builds regularly.
To prepare for my reply, I tested the most recent build of 10.8.1 today (VPinballX_GL-10.8.1-3582-b9fc92d-windows-x64-Release).

In fact, I was able to load and play all the tables without any issues that usually crash in VPX 10.8.0+Win11 (I tested Alien Star 3.0.1, Scared Stiff VPW 1.1, Terminator 2 G5K 1.25).
So far, so good.

Unfortunately, there are still bugs in 10.8.1 that prevent regular use.
Here’s what I found today:

- If you set a screen inclination (I use 16.4), the value resets to 0.0 after restarting VPX. Even setting it manually in the .ini file doesn’t help. (See screenshot)
- Pressing F12 during gameplay (to open the in-game table settings) works, but pressing F12 again to exit brings up the PinMAME volume dialog - unfortunately, it's hidden behind the playfield. (See screenshot)
- The biggest issue - and the reason I personally can’t participate actively testing the 10.8.1 builds (which is a pity) - is that the following bug still persists: https://github.com/vpinball/vpinball/issues/2030. This is happening for every table.
Since I play in stereo 3D (interlaced), this makes the 10.8.1 GL builds unusable for me.

For the original issue that I found running 10.8.0 in Win11 - I have the feeling that there is only a 'loose' relationship between the sound mode and the crash. I don't know why it changed over the last few weeks (automatic Win11 updates?) VPX is crashing now irrespective of the sound mode.

Personally, I would be happy to switch to 10.8.1 if it's usable.

One general note: I'm very grateful for what you and @toxieainc are doing for VPX. Great stuff!
.
.
.

![Image](https://github.com/user-attachments/assets/bc7ed542-3bc2-4fea-81f3-fd1aab8b3f3b)

![Image](https://github.com/user-attachments/assets/6cc56cdd-a1c5-4763-be0d-0ee95486177e)

**Comment by vbousquet** [comment]
As the object of this issue is fixed (no more crash), I will close the issue.
Regarding the other things reported in the discussion:
- 10.8.1 validate settings and discard invalid values. Inclination were validated against -15/+15, I will increase this range (16.4 seems incredible high but why not)
- double assignment of key is a user setup issue that already exists in 10.8. It is tracked in another issue about refactoring overall input
- stereo is already tracked in https://github.com/vpinball/vpinball/issues/2030 (note that this should be solved with latest build)

**Comment by jueank** [comment]
Hello @vbousquet ,
thank you very much for your explanations and your code adjustments & fixes!
I tried today’s build (VPinballX_GL-10.8.1-3830-dc1ac28-windows-x64-Release).

- Screen inclination setting is now preserved (thanks to your change of min/max angle to ±30°).
- Stereo 3D rendering issue is still present: image is still streched by a factor of 2 in width.

I couldn’t find any code changes in the commit list from today or yesterday that look like they would fix this bug. Did I miss something? Have you perhaps not submitted the change yet? Should I wait for a later build?

**Regarding the screen inclination (in case you’re interested):**
With regular 3D, a flat angle for the TV workes fine. But with a stereo 3D TV, a steeper angle (~16° vs. 12°) makes stereoscopic rendering more stable (=> it reduces tilting of the objects when moving your head).

A steeper TV angle also improves visibility of ramps and playfield structures (esp. 90s+ machines), while a flatter angle cuts off more of the top area and reduces realism.

**Comment by jueank** [comment]
@vbousquet 
Maybe you overlooked a part of my response. Here is it again:

_Stereo 3D rendering issue is still present: image is still streched by a factor of 2 in width.
I couldn’t find any code changes in the commit list from today or yesterday that look like they would fix this bug. Did I miss something? Have you perhaps not submitted the change yet? Should I wait for a later build?_
