### ISSUE TITLE
Default table triggers assertion

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#251]
**Describe the bug**
`assert(initial_state.state == live_state.state);` (Draw transparent objects. No DMD's) is triggered when running the CTRL+N table.

**To Reproduce**
DX9 rev 696/latest, F5 and F6 both cause it

**Comment by vbousquet** [comment]
Strangely, I can not reproduce. Could you post your video options (there must be something that differs here) ?

If you prefer, the fix is fairly easy:
- identify the RenderStatic or RenderDynamic offender
- add at the beginning
```
   RenderDevice *const pd3dDevice = g_pplayer->m_pin3d.m_pd3dPrimaryDevice;
   RenderDevice::RenderStateCache initial_state;
   pd3dDevice->CopyRenderStates(true, initial_state);
```
- add at the end of it
```
   pd3dDevice->CopyRenderStates(false, initial_state);
```

**Comment by vbousquet** [comment]
While fixing other stuff, I stumbled on one of these asserts regarding render state stability.
It is now fixed by https://github.com/vpinball/vpinball/pull/253/commits/c95980adb95c2a4cd6daa67d48811afdb5364673
I can't tell if this is the one you stumbled upon, but if it is, this can be closed

**Comment by toxieainc** [comment]
![grafik](https://user-images.githubusercontent.com/6709227/211223621-3fb2a5c2-b61a-4452-993d-60576e52553b.png)

Unfortunately still happens, here the video options..

**Comment by vbousquet** [comment]
Ok, was easier with the settings. Ball trails would change the render state and not restore it. It's fixed now
