### ISSUE TITLE
Image list option is not always populated when you add a new image.

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#26]
- Select some primitive -> hit F3 to open image editor -> add new image -> go back to editor side and see the options panel where you see primitive options -> open the image dropdown menu -> the new image is not there.
- To make it appear, you need to select some other object, then select the original primitive, open image dropdown list again, the new image is finally there.

This is just making editing slow.

**Comment by fuzzelhjb** [comment]
fixed in the next udate

**Comment by iaakki** [comment]
I see that this problem still happens with rev 120 (c473e7d).
