### ISSUE TITLE
Segments not displaying after LiveUI: full rework for live/startup property edition #1131

### ISSUE THREAD

**Issue by jsm174** [vpinball/vpinball#327]
Just to document this bug:

Working

fix more harmless warnings #1130
https://github.com/vpinball/vpinball/actions/runs/4399235811

![Screenshot 2023-03-17 at 8 00 31 AM](https://user-images.githubusercontent.com/1197137/225899989-67c524b1-c8ca-413b-a929-4d565f709850.jpg)

Non Working:

LiveUI: full rework for live/startup property edition #1131
https://github.com/vpinball/vpinball/actions/runs/4399770434

![Screenshot 2023-03-17 at 7 58 40 AM](https://user-images.githubusercontent.com/1197137/225900006-1f14ba3d-2b78-49ba-aed3-6a0c9d91bc11.jpg)

**Comment by cwscws** [comment]
Switching to cabinet view does not work anymore, niohing happens when clicking on cabinet view.

**Comment by vbousquet** [comment]
@jsm174 @cwscws These 2 (different) bugs should be fixed now. Can you confirm that it is ok with the absolute latest build on your setup ?

**Comment by jsm174** [comment]
Thanks for looking into this. Unfortunately I think the error is still there. 

I just checked out `update to latest #1159` https://github.com/vpinball/vpinball/commit/6702e77cc502fd5ae97131d16bffc6aee78c9e26 and the segments are still not displaying in Rock.
