### ISSUE TITLE
Whirlwind VR by Flupper Crash

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpinball#367]
**Describe the bug**

I noticed that the table would not launch anymore in 64bit VR-GL, latest. Going back with every build I found that v825 the table loaded fine but in v831 with the implementation of "LiveUI (full rework)" the table will not launch anymore.
**To Reproduce**
1. Go to 'VR-GL v825 and the table loads, go to v831 or any build after and the table will not load, with or without VR Enabled

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.
 Github will not allow me to post crash dump

[crash.txt](https://github.com/vpinball/vpinball/files/11124246/crash.txt)

**Comment by vbousquet** [comment]
As far as I can tell, this should be fixed in v937 (and you should also get some performance improvments). I will close for now, just tell me if it's not ok for you

**Comment by studlygoorite** [comment]
> As far as I can tell, this should be fixed in v937 (and you should also get some performance improvments). I will close for now, just tell me if it's not ok for you

Thanks but unfortunately with v937 and v939 the issue persists,  I still cannot load Whirlwind but also I cannot see any table in VR, just a black screen, tables load fine though :) If you think it should be working I can ask others to test these builds also and make sure it's not just me :)

**Comment by vbousquet** [comment]
No, don't need to disturb others, that must be me (I don't have a VR set, so the testing of the VR build is not that great, I may move this part of the code to OpenXR at some point, that would let me use the HoloLens emulator at least). I will investigate further on.

**Comment by vbousquet** [comment]
Ok, just found a stupid missing line for VR that could not be tested without a VR headset.
This build should fix it: https://github.com/vpinball/vpinball/actions/runs/4643870412
Please tell me if it's ok since I'm completely blind on that issue :)

**Comment by studlygoorite** [comment]
> Ok, just found a stupid missing line for VR that could not be tested without a VR headset. This build should fix it: https://github.com/vpinball/vpinball/actions/runs/4643870412 Please tell me if it's ok since I'm completely blind on that issue :)

No go yet sorry, still cannot load Whirlwind and all other tables I tested still just show a black screen....with v943. Went back to v925 and the tables that show a black screen are fine.

**Comment by gear323** [comment]
I have a Valve Index.  I'm a few versions 10.8 beta versions behind.  I'm going to install the latest now and will report back on Whirlwind and a few other tables.

**Comment by gear323** [comment]
Ok. I can confirm that with 10.8.925 VR was working well for me.   With the latest version, "943" the table loads and I can hear the ROM but I do not see anything in VR.  It is just a black screen as mentioned above.

**Comment by gear323** [comment]
Just confirmed that .939 also does not render in VR.  Same issue. Black screen and only hear rom

**Comment by gear323** [comment]
Went back to .925 again and everything seems to work fine.  I also tried Whirlwind (since that was what this bug report is for) and played a full game in VR and got multiball and a jackpot and extra ball and didn't have any lockups or any issues I could see.

**Comment by studlygoorite** [comment]
> Went back to .925 again and everything seems to work fine. I also tried Whirlwind (since that was what this bug report is for) and played a full game in VR and got multiball and a jackpot and extra ball and didn't have any lockups or any issues I could see or notice.
> 
> @studlygoorite Here are my Whirlwind table settings as well as my current VPXVR settings. Maybe you can copy them and see if whirlwind works again for you and if so maybe that will narrow down what issue.
> 
> ![image](https://user-images.githubusercontent.com/108252542/230731868-a5a3be71-cfd3-4e39-836d-764c241f435c.png) ![image](https://user-images.githubusercontent.com/108252542/230731909-206ea81c-ada4-4cd1-9bbe-e5ec2175edae.png)

Thanks for taking the time to post this, good news, I found a fix for my Whirlwind issue, if I double click the VPinballX_GL.exe the table folder automatically opens and I choose the table, this way Whirlwind will not launch. If I double click the VPinballX_GL.exe close the table folder that opens and choose "file" and then "open" and then choose a the table it launches no problem.

**Comment by vbousquet** [comment]
This should be solved in v953 available here: https://github.com/vpinball/vpinball/actions/runs/4672174707
Please tell me if it's ok for you so I can close this issue or investigate further

**Comment by gear323** [comment]
Installed 953 and still have the same issue.  The table starts, I can hear the ROM and interact with it by entering coins and starting the game but there is no picture at all in the VR headset.   

Valve Index - SteamVR 1.25.7 - Nvidia 3090

**Comment by studlygoorite** [comment]
> This should be solved in v953 available here: https://github.com/vpinball/vpinball/actions/runs/4672174707 Please tell me if it's ok for you so I can close this issue or investigate further

Same here, still a black screen. 
Quest Pro
RTX 3080
OpenComposite

**Comment by gear323** [comment]
Tried the latest 958 and now the table is seen in the headset again!   However there is graphical issues with the shadows or lights it seems. Black box under the ball and also under ramps and other toys etc on tables.

**Comment by gear323** [comment]
.960 does resolve the issues I was seeing and seems to work well for tables I have tried so far.  

@studlygoorite or @vbousquet,  I'm thinking that maybe this bug report should now be closed out, no?  Whirlwind seems to work fine and the issues with no image in the headset and graphical issues are not present in .960

**Comment by jsm174** [comment]
I think I'm back to not seeing the alpha numeric display in standalone. Will confirm when back at computer.

**Comment by studlygoorite** [comment]
Yep tables are no longer black for me too with v960 but I have other issues that I'll report separately.....after more testing.

**Comment by jsm174** [comment]
Just had a chance to check with the latest and the alpha numeric displays are not rending

![Screenshot 2023-04-16 at 12 41 56 PM](https://user-images.githubusercontent.com/1197137/232327428-cf08bf73-a7ff-4225-b6f8-eb68ec6e1efe.jpg)

Interesting enough, the other day (when they were rendering), I played with attempting to do the min float calculations on regular OpenGL and the displays would disappear. So this a long way of saying I guess them not showing might be related to precision?

```
void Shader::SetFloat(const ShaderUniforms hParameter, const float f)
{
   assert(0 <= hParameter && hParameter < SHADER_UNIFORM_COUNT);
   UniformCache* elem = &m_uniformCache[SHADER_TECHNIQUE_COUNT][hParameter];
   assert(elem->count == 0);
#ifndef __STANDALONE__
   elem->val.f = f;
#else
   elem->val.f = (f > 0 && f < FLT_MIN_VALUE) ? FLT_MIN_VALUE : f;
#endif
   ApplyUniform(hParameter);
}
```

**Comment by vbousquet** [comment]
So there was a few bugs reported here, all linked to the latest rendering refectoring:
- black screen => was a missing MSAA bug => now fixed
- alpha numeric => was a render sorting bug => now fixed
Therefore, I will close this issue to keep easier to follow. If there are other bugs, please open a dedicated issue with the description
