### ISSUE TITLE
Playfield image missing

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/vpinball#370]
Table: F-14 Tomcat, the playfield image is missing on 10.8 version 925 (latest). It's shown perfectly on 10.7.4 v400. Please find a solution. Thanks.
![Image 10 8 v925](https://user-images.githubusercontent.com/81928693/229714674-208d9d30-2e15-4ecb-b939-7f7a87556105.jpg)
No playfield image 10.8 v925
![Image 10 7 4 v400](https://user-images.githubusercontent.com/81928693/229714787-40cb9f6e-ffc9-4983-8978-0b838726ba0c.jpg)
Playfield image shown correctly 10.7.4 v400

**Comment by vbousquet** [comment]
I can not reproduce this bug (it looks like it's Wrd version of the table, and I don't think the table is available on the net). Beside this part of the rendering code has been mostly rewritten. So, I will close for now but if you are still experiencing this bug, please reopen and perhaps you could share the table file with me to do some more testing. Regards

**Comment by JorgePedro65** [comment]
I reopened the issue. Please tell me how can I share the file with you.

**Comment by vbousquet** [comment]
This time, this should be fixed. By the way, this is a very very nice version of the table. Thanks!

**Comment by maselasm** [comment]
i have the same issue with spiderman Vault edition table. playfield is missing. its all black 
![Screenshot (1350)](https://user-images.githubusercontent.com/130717277/231914863-9b289c36-ed71-4840-81fb-84d1927df3e7.jpg)

**Comment by vbousquet** [comment]
@maselasm this should be fixed in latest pre-alpah (v975)

**Comment by drinkcristal** [comment]
Hi,

I am using VPinballX-10.8.0-980-aedf6dc-Release-win-x86 and still have the same issue regarding the playfield missing

I am using a laptop with Nvidia graphics card (latest firmware).

If there is a newer version of software to try, please advise?

**Comment by passionforpins** [comment]
Works fine for me using VPinballX-10.8.0-980-aedf6dc-Release-win-x86 and x64.
vpinmame-sc 3.26
windows 10 22h2
nvidia gtx 1060 6gb
Also the wrd1972 version of F-14 is working fine in all 32 and 64 bit NON-GL vpx 980 and 10.7.4. I cannot test GL however
I would suspect previous poster has limited video memory on his laptop so should try reducing elements detail level
![smve-2 1-dt-pups](https://user-images.githubusercontent.com/52011304/233851470-c658fde7-6cbf-434f-b63c-cfb2cbbd9680.jpg)

**Comment by drinkcristal** [comment]
Hi, thanks for the suggestion. I dumbed down the texture and element details to the lowest possible and I still have the problem.

I think it is a laptop / Nvidia card combo issue. I normally play in VR and have no issues with 10.7 releases.

![image](https://user-images.githubusercontent.com/108242910/233867309-c90d2237-f512-46b3-a32c-bab78b2fa241.png)

I will see if future releases fixes my issue 

Cheers,

**Comment by JorgePedro65** [comment]
I tried new 999 and the issue was solved. I give permission to my friend Vincent Bousquet to close it or not, it's his decission.

**Comment by drinkcristal** [comment]
I believe my issue is a set up / registry issue. I have used a separate windows install on the same laptop and the issue is not evident now.

**Comment by vbousquet** [comment]
Ok. Thanks all. Closing then

**Comment by exoduscl** [comment]
I'm facing the same issue with some tables: Attack From Mars and Terminator 2 load and work fine, but the playfield is black.

I have everything updated, tried GL and same result.
