### ISSUE TITLE
VR No longer works 

### ISSUE THREAD

**Issue by gear323** [vpinball/vpinball#504]
**Describe the bug**
VR does not work in latest version.   Table loads but nothing is rendered in the headset.  Can hear ROM audio and coins etc. 

**To Reproduce**
load any table and try to play it in VR

**Versions & Settings**
Win 11 22H2
Valve Index 
Steam VR  1.25.8
Nvidia 3090 
VPX 10.8 1165

**Comment by gear323** [comment]
As a test I reverted back to 10.8. 925 to ensure everything is working with my headset and it played find.  Went back to 1165 and blank screen again.

**Comment by retro27** [comment]
v1165 I'm getting a blank image, you can hear all the sounds etc. I have rolled back to v1164 and working ok in VR
I tested v1165 in desktop mode and it works ok,

**Comment by vbousquet** [comment]
Reopened since I saw report in Discord that this is not fixed in 1174

**Comment by studlygoorite** [comment]
I can't test because OpenComposite no longer works since the dll names change :)

**Comment by vbousquet** [comment]
1176 should fix it
Regarding dll naming, I won't be of great help since I don't really know how this works. @toxieainc perhaps you may know better ?

**Comment by studlygoorite** [comment]
Actually you were right, changing the name of the OpenComposite .dll worked.....thanks.

**Comment by retro27** [comment]
hi i've just tried 1176 and i'm still getting the same problem, I just get a black screen in VR in steamVR

**Comment by gear323** [comment]
1176 does not work in VR. lots of Shader errors.

**Comment by vbousquet** [comment]
These message box are likely due to an incorrect install (likely outdated to tweaked shaders). You should start a fresh one (download/unzip/run)

**Comment by gear323** [comment]
> These message box are likely due to an incorrect install (likely outdated to tweaked shaders). You should start a fresh one (download/unzip/run)

I have replaced all files each time and extracted it a few times now.. No change?

**Comment by gear323** [comment]
I went ahead and renamed my shaders folder to Shaders_old and copied all of the files again and still get all of those errors.  Note that the directory it is looking for shaders in the error does not exist on my computer.

**Comment by vbousquet** [comment]
Could you post your settings file (vpinballx.ini) ?

**Comment by gear323** [comment]
> Could you post your settings file (vpinballx.ini) ?

1178 is working for me.  Looks like with 1177 you guys changed the name of the Exe file to VPinballX_GL64.exe.  My front ends and my windows shortcuts and batch files were pointing to the old name causing me to use the old EXE and the new shaders. 

anyway.  I only did basic test but VR seems to load up and play now again for me

**Comment by toxieainc** [comment]
> Actually you were right, changing the name of the OpenComposite .dll worked.....thanks.

Just for future reference: What i did only affects the linking (so all on our/developer side), the actual dll can then be just renamed to match 'our' dll.
