### ISSUE TITLE
Latest GL doesn't play any table and hangs

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#610]
**Describe the bug**
When ;launching a table in cabinet mode with latest GL version ( rev 1294) results that the visual player gets in not responding and hangs
changing "synchronisation mode" to any setting doesn't make  any difference

**To Reproduce**
1. open GL version (64 bit)
2. open table
3. hot f5
4. table loads, but hangs

**Expected behavior**
launching table normally and play a game

**Screenshots**
![image](https://github.com/vpinball/vpinball/assets/48748234/b7b7ffd6-136e-421d-b8c1-eead98bc014d)

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.
[crash.zip](https://github.com/vpinball/vpinball/files/11933146/crash.zip)

**Versions & Settings**
 - VPX: 10.8 64 bit (DX9 and GL) rev 1294 (1297 tested as well)
 - Windows version W11 22h2
 - GPU and video settings if applicable RTX 3080
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
[VPinballX_ini.log](https://github.com/vpinball/vpinball/files/11933158/VPinballX_ini.log)

 - 
 
**Additional context**
NA

**Comment by vbousquet** [comment]
This may be fixed in 1305. Could you give it a try and confirm I can close ?

**Comment by wiesshund** [comment]
This is fixed as far as my testing with 1308
was able to launch in cab view and play fine.

**Comment by MikedaSpike** [comment]
I tried 1308, but still have the same behavior
![image](https://github.com/vpinball/vpinball/assets/48748234/96efd037-9101-4c04-8a78-2b1d28eb037f)

[crash.zip](https://github.com/vpinball/vpinball/files/11944143/crash.zip)

**Comment by wiesshund** [comment]
Mike does  vpx leave you a log at all?

Or something in windows event manager?

Can you give your PC info, hardware, driver versions etc.
I cant reproduce on either machine that i have that can run openGL 4 stuff

**Comment by MikedaSpike** [comment]
Maybe I was unclear.
Here's a recap of the issue with all the info: 
Operating system W11 22h2 build 22621.1848
VPinba GL 64 bit  10.8 rev 1308
AMD Ryzen 7 5700X - 32GB 
Gigabyte RTX 3080 
Nvidia GeForce driver 536.40

Running GL version with VR, is working fine (well, no crashes, but huge frame drop in compare with older versions)
Running GL version in cabinet mode, the table can be loaded into the editor, but launching the table, it directly freezes and hangs)

2 events in event log:
1)
Log Name:      Application
Source:        Application Hang
Date:          5-7-2023 05:54:45
Event ID:      1002
Task Category: Hanging Events
Level:         Error
Keywords:      
User:          SYSTEM
Computer:      Pinball
Description:
The program VPinballX_GL64.exe version 10.8.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

2)
Log Name:      Application
Source:        Windows Error Reporting
Date:          5-7-2023 05:54:43
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      
User:          PINBALL\Mike DA Spike
Computer:      Pinball
Description:
Fault bucket 2136213536109890655, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: VPinballX_GL64.exe
P2: 10.8.0.0
P3: 64a339ee
P4: 669b
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fec4bf7f-5253-4de3-848b-f76b123850cc.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.fd5ca63f-1fc5-4581-aa89-387ce6c64e7a.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.edd3e2b6-8baa-4590-913c-440607b79109.tmp.txt
\\?\C:\Users\micha\AppData\Local\Temp\WER.0d4d9459-d373-4bc8-a279-d5a907121589.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8cbc8c12-a063-49e4-8347-58429a9f4e96.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_VPinballX_GL64.e_1f38b58e2a9728023ad3377373f9c5019568338_dd70fe54_08a2a758-cd6f-47ce-902b-a888dd7d5417

Enabling debug in INI file gives me the same vpinball.log as it was not turned on (only in the tables dir instead of the the directory of the IN Ifile)
Including this log with the windows error report in the attached zip file 

[VPX_CrashFiles.zip](https://github.com/vpinball/vpinball/files/11953804/VPX_CrashFiles.zip)

Turing of Full screen exclusive mode, gives the same result

Tried to capture a video of it, but , won't see the first part when launching the table (it shows black, but it is actually the PF)
https://youtu.be/U9Kqeokum8Y

**Comment by vbousquet** [comment]
@MikedaSpike There has been quite some fixes in latest build. Could you give a try to the latest and report if it is ok for you (I can't rperoduce this bug on my side) ?

**Comment by vbousquet** [comment]
@MikedaSpike I saw a post on discord where you seem to be using GL ok, so I will close for now

**Comment by MikedaSpike** [comment]
Yes, first tests it was working, but didnt respond yet as I was nut 100% sure as I need more testing. It didnt show this error, so I'm ok with it (and thanks for all your hard work)

**Comment by vbousquet** [comment]
No problem, just checking what's left since the 10.8 release looks nearly ready
