### ISSUE TITLE
Crash when i click configure "keys, nudge and dof"

### ISSUE THREAD

**Issue by CultAce** [vpinball/vpinball#935]
**Describe the bug**

The crash occurs when I attempt to configure "keys, nudge, and depth of field.

**To Reproduce**
1. Go to 'Preferences.'
2. Click on 'Change keys, nudge and df.'
4. Crashes

[VPinballX.zip](https://github.com/vpinball/vpinball/files/12908975/VPinballX.zip)

**Versions & Settings**
 - VPX: [e.g. 1.8.0 Final Revision 1604
 - Windows 10

[crash.zip](https://github.com/vpinball/vpinball/files/12908976/crash.zip)

**Comment by studlygoorite** [comment]
It looks to me that this started in v1593 (64bit VPX)

**Comment by toxieainc** [comment]
Should be fixed again, please verify.

**Comment by toxieainc** [comment]
Just tried to repro this with my own builds, or the github debug builds, but i fail to repro.
I can only repro with the github 32bit DX9 builds, and the last non-crashing one there was 1585, the first crashing one 1591, so @vbousquet to the rescue, please.  ;)

**Comment by studlygoorite** [comment]
> Should be fixed again, please verify.

Now working here with v1610 64bit, thanks

**Comment by wiesshund** [comment]
Still crashes unless you touch other dialogs 1st
Also crashes if no ini pre-present, does not create from vpx7 registry

[vpx.zip](https://github.com/vpinball/vpinball/files/12919534/vpx.zip)
[VPinballX.zip](https://github.com/vpinball/vpinball/files/12919544/VPinballX.zip)

**Comment by vbousquet** [comment]
I have just pushed fixes that may solve this (I can't reproduce on my end). Is it ok for you ?

**Comment by wiesshund** [comment]
> I have just pushed fixes that may solve this (I can't reproduce on my end). Is it ok for you ?

Negative, issue still persists

[crash.zip](https://github.com/vpinball/vpinball/files/12923001/crash.zip)
[vpinball.log](https://github.com/vpinball/vpinball/files/12923005/vpinball.log)

If i touch another prefs dialog, it is fine, and seems to remain fine until memory is cleared

**Comment by toxieainc** [comment]
Same for me still, x86-32bit DX release only, and unfortunately still only with the official github build.  :/

**Comment by vbousquet** [comment]
Fixed in latest
