### ISSUE TITLE
Flexdmd does not close with VP GL

### ISSUE THREAD

**Issue by Pinbalbilly** [vpinball/vpinball#971]
**Describe the bug**
Flexdmd does not close with VP GL

Steps to take:

Load a table that has flexdmd on any latest version of VP 10.8 GL, for example 1622, start the table and close it, you will see that the dmd does not close.  Do the same operation but with version VP 10.8 1622 DX, when you close you will see that on this occasion the dmd does close.

Table:
https://vpuniverse.com/files/file/16321-spongebobs-bikini-bottom-pinball-vpw/

**Expected behavior**
The dmd would have to be closed in both versions

**Versions & Settings**
 - VPX:
VPinballX-10.8.0-1622-7c11239-Release-win-x64 
VPinballX_GL-10.8.0-1622-7c11239-Release-win-x64

**Additional context**
This is a problem that I have always encountered since using VP 10.8 GL.
Use Flexdmd 1.9.

Thank you for your work

**Comment by droscoe** [comment]
I was just about to add this same issue

**Comment by vbousquet** [comment]
This should be solved with latest change (player close has been cleaned up and thoroughly tested), so I will close it.
Note that PinballY has a very agressive way of closing VPX which does not give enough time to VPX and will result in killing VPX app before the script had the time to properly close Flex/Pup/whatever. I don't think this is a VPX bug but more a PinballY bug

**Comment by Windbury** [comment]
This thread was closed, but I have the latest version of VPX and it still occurs. Could it be due to a problem with how I installed FlexDMD?
